### PR TITLE
Make the build a bit faster

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by edenhill** [comment]
This fails on osx:
https://travis-ci.org/edenhill/librdkafka/jobs/106722515

**Comment by thedrow** [comment]
Can the tests run in parallel?

**Comment by edenhill** [comment]
The tests are run in parallel already.

What is the underlying problem with the current build speeds on Travis?
It is not a problem I've really encountered.

**Comment by thedrow** [comment]
No problem. I just pick low hanging fruits if I see them.

**Comment by thedrow** [comment]
Done. I'll file an issue about ccache not being available on OSX.

**Comment by thedrow** [comment]
See https://github.com/travis-ci/travis-ci/issues/5567 for relevant travis issue.

**Comment by thedrow** [comment]
@edenhill Done.

**Comment by DEvil0000** [comment]
how about using the real core number instead of -j2?
something like this:
cpuCount=`lscpu -p | grep -v ^# | wc -l`
make -j$cpuCount

**Comment by thedrow** [comment]
The real core number is not available in Travis due to a bug in their virtualization layer.
Each worker has two cores.

**Comment by edenhill** [comment]
Thanks @thedrow!

**Pull request merged**
