### PR TITLE
SASL: Windows SASL implementation via SSPI (#888)

### PR DESCRIPTION
**Pull request by zyzil**
Additional changes to support Kerberos authentication from Windows
using SSPI.

### CODE REVIEW

**Comment by zyzil** [comment]
With this changes I am able to successfully authenticate with Kafka from a Windows machine.  Here are some details about the environment:

I am using Windows Active Directory to authenticate.
Kafka is running on a kerberos enabled Cloudera cluster running on Oracle Linux 6.8.
I am using the rdkafka_example to produce message. The command line arguments look like this:

-P -t librdkafka -b kafka.mydomain.net:9092 -X security.protocol=SASL_PLAINTEXT -X sasl.kerberos.service.name=kafka/kafka.mydomain.net@MYDOMAIN.NET -X sasl.kerberos.principal=kafka -d security,protocol,broker.

**Comment by edenhill** [comment]
You know what would be really great? If you could write a blog post outlining the steps needed to deploy this in practice, including broker config, any AD specific stuff, etc.
I think there are alot of people that are looking into this setup but are thrown off due to lack of information and guides.

**Comment by zyzil** [comment]
I can definitely understand.  Anything Kerberos related ends up being a daunting task and throw AD into the mix and you have even more fun.  I don't have a full picture of the steps currently because others helped setup the servers, but I wouldn't mind learning more about it.  I can create a small test domain and integrate ZooKeeper/Kafka into it via Kerberos/AD.  That should be easy enough to document.  I'll make it a little pet project and let you know when I have some documentation.

**Comment by edenhill** [comment]
@MaximGurschi Do you want to try this PR out in your setup?

**Comment by MaximGurschi** [comment]
Am getting a:
java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag
)]

on the broker with this.

**Comment by gwenshap** [comment]
@edenhill Can't wait to see this merged - and even more excited about a possible @zyzil blog.

**Comment by edenhill** [comment]
Thanks for this!

**Comment by edenhill** [comment]
@zyzil and @MaximGurschi  Would you like to add any additional steps needed on the client-side for using SASL with Win32 on the librdkafka wiki-page here?:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by edenhill** [comment]
And remember, you are both heroes.

**Comment by MaximGurschi** [comment]
Once I setup everything again from start to finish will update with the steps. I'll allocate some time towards the end of the week/early next week.

Thanks all again, good job!

**Comment by MaximGurschi** [comment]
Hi Magnus, I am ready to put the Windows manual on the WIKI. Should it go on the same page (https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka) or should there be a dedicated Windows SSPI page?

**Comment by edenhill** [comment]
@MaximGurschi Awesome! That's up to you, if it is too meaty it probably makes sense to have  its own wiki page (reference it from the original page), otherwise integrate into the existing one.

**Comment by MaximGurschi** [comment]
I've created the page here:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka-on-Windows

Please let me know if you have any suggestions/remarks.

**Comment by edenhill** [comment]
@MaximGurschi This is really great!

Some minor things:
 * use ALLUPPERCASE for all variable fields, e.g. "domain\Zookeeper_.." should probably be "DOMAIN\Zookeeper_..", 
 * The \*\*\_HOST.. notation doesn't work in code sections
 * what is dp0? `%~dp0../..`
 * HOST.fully_qualified should probable be HOST_FQDN
 * Describe all variable fields (DOMAIN, HOST, etc..) at the start of the wiki post so people know what they need to set up/define.
 * Make a note that zookeeper auth is optional and mark those chapters as optional, I'm guessing librdkafka users will mostly care about authentication the client.
 * It would be great if you provided some example output from rdkafka_example.exe with the `-d security` option so that people can see what a succesful auth looks like.

 
Big thanks!

**Comment by MaximGurschi** [comment]
Cheers Magnus, great feedback! What do you say to the update?

**Comment by edenhill** [comment]
Looks great!
I'm still curious, what is `%~dp0..`?

**Comment by MaximGurschi** [comment]
:)
I placed it in the WIKI as well:
The %~dp0 (that’s a zero) variable will expand to the drive letter and path of the batch file.

**Comment by edenhill** [comment]
Windows magic :)

**Comment by edenhill** [comment]
Thanks to both of you for all your work with SASL on Windows, this is open source at its finest!

**Pull request merged**
