### PR TITLE
Store offsets corresponding to ctrl messages

### PR DESCRIPTION
**Pull request by mhowlett**
resolves: https://github.com/edenhill/librdkafka/issues/2539

### CODE REVIEW

**Comment by edenhill** [comment]
Can you rebase this on latest txns branch?

**Comment by edenhill** [comment]
Can you rebase this on latest master?

**Comment by mhowlett** [comment]
needs to go in order for the v1.4.0 .net integration tests to pass. IIRC you'll need to check carefully, you'll have opinions.

**Comment by edenhill** [comment]
Continued in #2743

**Pull request closed without merging**
