### PR TITLE
ACL Admin Apis: CreateAcls, DescribeAcls, DeleteAcls

### PR DESCRIPTION
**Pull request by emasab**
Hi, I've implemented the ACL admin apis.
The things that I've checked are:

- regression tests with versions 0 and 1 of the API client side against versions 0 or 1 server side.
- memory leaks with the valgrind mode
- removed all warnings
- formatted the changed code with the clang-format that I've created following the "librdkafka C style guide", using git clang-format-9 <base>
- added a make format target to format all the c, cpp and h files (but not run it)

In order to make the 0081-admin test work this change must be applied to trivup:
https://github.com/edenhill/trivup/pull/10

I've tried to follow the existing coding style, naming and design but given that the change is not trivial there could be things that are missing or need some change. The formatting rules are open to any change that is needed, I haven't found a rule that adds spaces before parenthesis always except in function calls.

### CODE REVIEW

**Comment by emasab** [comment]
rebased

**Comment by emasab** [comment]
Did you have time to check this one?
Best

**Comment by emasab** [comment]
rebased, any plans for this PR?

**Comment by edenhill** [comment]
Thank you for your patience, we'll be looking at this PR after v1.4.0 is released (soon!).

**Comment by emasab** [comment]
Thanks for the update!

**Comment by emasab** [comment]
rebased and now, with the latest trivup, the tests are passing

**Comment by emasab** [comment]
Hello, I've rebased this one after the addition of the RD_KAFKA_OP_DELETERECORDS, RD_KAFKA_OP_DELETEGROUPS,               RD_KAFKA_OP_DELETECONSUMERGROUPOFFSETS, RD_KAFKA_OP_ADMIN_FANOUT. There where different conflicts, even some that could cause bugs, for example same values of RD_KAFKA_EVENT_*_RESULT (I've changed those values). Please merge soon. If not in master, in the branch of the next release. Thanks

**Comment by edenhill** [comment]
Will address this after v1.6.0 is released, thanks for your patience.

**Comment by yanivmn** [comment]
Hi edenhill, what is your plan regarding this PR?

**Comment by edenhill** [comment]
Sorry for the long delay, too much stuff to do, I'll revisit this after the 1.7.0 release.

**Comment by dimpavloff** [comment]
Hi, are there any plans to merge this for 1.8 or 1.9?

**Comment by emasab** [comment]
Hi, are you looking to auto generate the code from the protocol specification? In that case do you want to merge this one or will it be replaced by auto generated code?

**Comment by treydempsey** [comment]
Can you share with us why this has been delayed so long? It seems like a high quality addition to the code base and something I and many others want.

**Comment by edenhill** [comment]
I took the liberty to rebase this on latest master and fix the style issues induced by the recent introduction of clang-formatting in the project.

**Comment by edenhill** [comment]
Will review soon. This is targeted for the next release.
Sorry for the delay..again, always.

**Comment by emasab** [comment]
Thanks Magnus, don't worry I understand that as this is already available in the Java client and it's for administrative operations, has lower priority than other core apis. Hope this time it'll make it into the release, let me know if there are changes to make.

**Review by edenhill — APPROVED** [review]
This is stellar work, @emasab !

**Comment by dimpavloff** [comment]
Thanks @emasab and @edenhill for getting this merged!

**Pull request merged**
