### PR TITLE
adds check of defined LIBRDKAFKA_STATICLIB to enable static library

### PR DESCRIPTION
**Pull request by skarlsson**
I currently build librdkafka out of source with cmake but it would be convenient to make it possible to build static libs. This pull request only enables that - it does not change anything for existing builds.

### CODE REVIEW

**Comment by edenhill** [comment]
Looks good, can you add a small snippet to README.win32 on when (and how) to use LIBRDKAFKA_STATICLIB?

**Comment by skarlsson** [comment]
sure, but as I said I needed to build outside of librdkafka source tree so i ended up just globbing all files except rdkafka_sasl.c


this is what i did in my CmakeLists.txt

...

file(GLOB librdkafka_files
  ${CMAKE_CURRENT_SOURCE_DIR}/../librdkafka/src/*.c
  ${CMAKE_CURRENT_SOURCE_DIR}/../librdkafka/src/*.h
  )

file(GLOB librdkafka_cpp_files
  ${CMAKE_CURRENT_SOURCE_DIR}/../librdkafka/src-cpp/*.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/../librdkafka/src-cpp/*.h
  )

list(REMOVE_ITEM librdkafka_files ${CMAKE_CURRENT_SOURCE_DIR}/../librdkafka/src/rdkafka_sasl.c)

add_definitions(-DLIBRDKAFKA_STATICLIB)
add_library(librdkafka STATIC ${librdkafka_files})
add_library(librdkafkacpp STATIC ${librdkafka_cpp_files})

Do you want this alternative build explained in the README.win32?

And BTW I also noticed that that openssl 1.1.0+ changed the lib names

**Comment by edenhill** [comment]
There's ongoing work by @olibre to add proper cmake support to librdkafka, as an alternative to VS and mklove: https://github.com/olibre/cmake-for-rdkafka/issues/1

I dont think you need to describe the cmake process, just mention the define and why it is needed.

And librdkafka only supports OpenSSL 1.0 at this point.

**Comment by skarlsson** [comment]
Sure, I'll add a comment. 

I did not test running anything against a ssl enabled kafka broker but everything compiles with 1.1.0c anv visual studio 2015 update 2 (and runs fine against a normal kafka)

**Comment by edenhill** [comment]
Thans Svante!

**Pull request merged**
