### PR TITLE
Win32 sspi

### PR DESCRIPTION
**Pull request by zyzil**
I need to be able to use rdkafka-dotnet with a Kerberos enabled Kafka system and found the work you had started on using SSPI on Windows.  I have continued that work and with these changes can now authenticate via Kerberos/SASL and produce to our Kafka system.  The win32_sspi branch was quite a bit behind master, so I merged master into the branch before making the changes.  I was hoping that this would make it easier to get these changes back to master; however, please let me know if this approach is not favorable and I can do whatever is necessary to correct it.

Thanks!

Kevin

### CODE REVIEW

**Comment by edenhill** [comment]
Wow, interesting!

# Rebase
First a nitpick: can you rebase from master instead of merging it, to avoid all the extra commits?
Do this:
````
git checkout master
git pull origin master
git checkout sspi_branch..whatever
git rebase master
git push --force origin sspi_branch_whatever  # overwrites previous history in branch
````

# What, how, when, why, who

I never got SSPI to work so I'm very excited about this.

Please tell me about your setup:
 * are you using Windows AD to authenticate, or Kerberos KDC?
 * are your browsers running on Windows aswell?
 * what does your librdkafka client config look like?

**Comment by zyzil** [comment]
Sorry, I'm still working out the rebase.  

To answer your questions:

I am  using Windows Active Directory to authenticate.  
Kafka is running on a kerberos enabled Cloudera cluster running on Oracle Linux 6.8.
I am using the rdkafka_example to produce message.  The command line arguments look like this:

-P -t librdkafka -b kafka.mydomain.net:9092 -X security.protocol=SASL_PLAINTEXT -X sasl.kerberos.service.name=kafka/kafka.mydomain.net@MYDOMAIN.NET -X sasl.kerberos.principal=kafka -d security,protocol,broker.

**Comment by edenhill** [comment]
I'm not really sure what you did there, but now all commits (your own and the branch diff) is squashed up in one single commit :/.

Let me rebase the win32_sspi branch for you, then you fetch that and apply your changes (and your changes only) cleanly on that and push that to the PR.

**Comment by zyzil** [comment]
I'm still relatively new to Git.  I tried rebasing with your suggestions but it still wanted to have all the individual commits.  Sorry for the inconvenience.

Kevin

**Comment by edenhill** [comment]
@zyzil Git is hard, no need to apoligize.

I've rebased the win32_sspi branch (force-pushed) now.
The easiest approach for you now is probably to make a clean git clone of librdkafka, check out the updated win32_sspi branch, and the copy your stuff over to that repo and commit it. This should result in a diff only containing your fixes. Then you create a PR of that.

Let me know if you need assistance.

**Pull request closed without merging**
