### PR TITLE
Make dynamic MinGW build copy DLLs instead of trying to manipulate PATH

### PR DESCRIPTION
**Pull request by neptoess**
My stab at fixing the issues highlighted in the #3607 chat recently. When running locally, the two librdkafka DLLs were the only issue. Copying the DLLs to the same folder as the EXE is a much more common practice on Windows than adding the folder the DLLs live in to PATH, so I'm giving this a shot.

### CODE REVIEW

**Comment by neptoess** [comment]
Hmm, Travis didn't fire off the dynamic MinGW build (https://app.travis-ci.com/github/edenhill/librdkafka/builds/248597005). I don't think I'm able to trigger it either. Can you help me out there @edenhill ? Thanks

**Comment by neptoess** [comment]
> @neptoess The dynamic build requires a tag, you can just remove that "if: .." statement in .travis.yml

Thank you. Removed the `if`. Looks like my fix worked. My guess is that something changed on the Travis end where the old approach of updating `PATH` instead of copying the DLLs stopped working. Relying on environment variable updates is a major dice roll on Windows, so the "copy the DLLs" approach is, in my experience, a much more common practice.

**Review by edenhill — APPROVED** [review]
LGTM!
Can you rebase on latest master and reinstate the Dynamic travis builder that I commented out and reinstate the "if: tag IS PRESENT" ? Thanks

**Review by edenhill — APPROVED** [review]
LGTM
Thanks!

**Comment by edenhill** [comment]
Thank you for so quickly helping out with this, much appreciated!

**Pull request merged**
