### PR TITLE
KIP-62: add support for max processing time (max.poll.interval.ms)

### PR DESCRIPTION
**Pull request by edenhill**
Changed defaults:
 * session.timeout.ms = 10000

### CODE REVIEW

**Comment by ijuma** [comment]
Nice! Do we track these config default changes somewhere so that we can tell users in upgrade notes and such?

**Comment by edenhill** [comment]
@ijuma Yep, something like "Default changes" here: https://github.com/edenhill/librdkafka/releases/tag/v0.11.4

**Comment by ijuma** [comment]
Sounds good.

**Comment by edenhill** [comment]
Added `rebalance_reason`.
A `max_poll_interval` metric would definitely be useful, but requires a lock rather than an atomic, so will leave this until it is really needed.

**Comment by edenhill** [comment]
Added `rebalance_reason`.
A `max_poll_interval` metric would definitely be useful, but requires a lock rather than an atomic, so will leave this until it is really needed.

**Comment by edenhill** [comment]
Added `rebalance_reason`.
A `max_poll_interval` metric would definitely be useful, but requires a lock rather than an atomic, so will leave this until it is really needed.

**Pull request merged**
