### PR TITLE
Produce batch partition per message flag

### PR DESCRIPTION
**Pull request by barrotsteindev**
for #1604

### CODE REVIEW

**Comment by barrotsteindev** [comment]
@edenhill ,
I am having trouble with the.merge conflicts as I am not familiar with the retry_fixes changes.
It would be a great help if you could help me with that.
Thanks in Advance

**Comment by edenhill** [comment]
You should base your branch on retry_fixes and when creating the PR you set the base branch to retry_fixes.

**Comment by barrotsteindev** [comment]
Sorry guess I didn't get it the first time.
Will fix asap.

**Comment by barrotsteindev** [comment]
#1628 opened new pull request to different branch

**Pull request closed without merging**
