### PR TITLE
cosmetic changes

### PR DESCRIPTION
**Pull request by joseAndresGomezTovar**
+ add support to vs2013 and vs2015 (using
Condition="'$(VisualStudioVersion)'=='12.0')
+ remove openssl dependency (using #pragma comment(lib)) with WITH_SSL=0
definition

### CODE REVIEW

**Comment by edenhill** [comment]
AppVeyor build fails: https://ci.appveyor.com/project/edenhill/librdkafka/build/0.9.1-post437#L1273

**Comment by joseAndresGomezTovar** [comment]
let me check it this night (UTC+1) (searching in google appears a _"working directory issue..."_[https://github.com/dantarion/SF5DInput/pull/16/files])

**Comment by joseAndresGomezTovar** [comment]
do you know if you are using libraries.v140 appveyor?
Its the first time I see appveyor but  at line 10
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.

apparently is using vs2015 isn´t it?

**Comment by edenhill** [comment]
The toolchain wasn't defined so I set it to build both VS 13 and 15, let's see what happens.

**Comment by edenhill** [comment]
Fails for both of them
https://ci.appveyor.com/project/edenhill/librdkafka/build/0.9.1-post442

**Comment by joseAndresGomezTovar** [comment]
works well locally, I keep searching (I use _Win32OpenSSL-1_0_2j_ of

 [https://slproweb.com/products/Win32OpenSSL.html](url)

**Comment by joseAndresGomezTovar** [comment]
There is an error with the library directory ... that all folks

**Comment by mhowlett** [comment]
To the extent that I know what I'm looking at here, this looks fine to me except i'm wondering about the absolute paths in win32/tests/tests.vcxproj.

**Pull request closed without merging**
