### PR TITLE
Simplify group assignor init / config

### PR DESCRIPTION
**Pull request by mhowlett**
some things here seem unnecessarily complicated / general. am i missing anything important?

haven't tested this - if it looks right to you, will do that.

### CODE REVIEW

**Comment by edenhill** [comment]
The group protocol is generic and not specific to consumers (see kafka connect), the code reflects this and is prepared for supporting future protocol types as well as user-pluggable ones, which might have been a premature generalization, but I'm not sure what the benefit is of removing this generalization?

Also, make sure the tests pass locally, there are compilation warnings and test failures due to this change.

**Comment by mhowlett** [comment]
> The group protocol is generic and not specific to consumers (see kafka connect), the code reflects this and is prepared for supporting future protocol types as well as user-pluggable ones, which might have been a premature generalization, but I'm not sure what the benefit is of removing this generalization?

yep - reverted this. The main aspiration of this PR was to remove `rkas_enabled` and related logic (thoughts on that?), which caused me a not insignificant amount of wasted time working out why this code was the way it was. I then got carried away depreciating the config property. you're right, removing it won't meaningfully help anyone.

the only way assignors can be set (afaict) is via this config property, and they're always enabled, so I think the stuff i've removed should just be removed.

apologies for opening quickly - wanted your high level thoughts quickly and couldn't be bothered doing any more yesterday. I've now fixed the warnings and bugs and run the integration tests.

**Comment by mhowlett** [comment]
[note: deleted previous comment that demonstrated i didn't read yours]

yeah, agree that having the group.protocol.type config isn't a big deal and it's better not to remove it. I added some clarification to the docs in the current state of this PR instead of removing it.

the user-pluggable related code caused me some amount of wasted time, so i still think it's an improvement to either remove it made clearer (current PR state removes it).

**Comment by edenhill** [comment]
I don't really understand the reasoning behind these changes.

The code is prepared for (but does not yet expose) user-pluggable assignors, I do appreciate that unused abstractions can be removed to reduce complexity, but that should not be a reason in itself to change existing code that does not have issues, since any code change risks introducing bugs.
Also, the suggested patch breaks abstraction of an isolated part of the code (assignors_init()..).

I'd like to understand the reasoning for this change to understand why it is deemed warranted, what does it enable?

**Comment by edenhill** [comment]
See #2284

**Comment by mhowlett** [comment]
My reasoning was just reduce complexity in something that caused me to waste some time + make it clear in the user facing config that a property was currently pointless. Thanks for the context, makes sense!

**Pull request closed without merging**
