### PR TITLE
Small change to proprogate the WITHOUT_WIN32_CONFIG flag to the build

### PR DESCRIPTION
**Pull request by mattclarke**
I think this small change is needed to enable overriding of the settings in src/win32_config.h.

Perhaps @raulbocanegra could check this?

### CODE REVIEW

**Comment by raulbocanegra** [comment]
You are right. I should have added this on my last PR. Thanks! :-)

**Comment by edenhill** [comment]
Are you guys happy with this?

**Comment by raulbocanegra** [comment]
Yep

**Comment by shilf** [comment]
What does WITHOUT_WIN32_CONFIG do?Is WITHOUT_WIN32_CONFIG necessary?

**Comment by mattclarke** [comment]
It allows one to override/replace the settings in win32_config.h without editing that file directly.

If you are happy with the defaults in win32_config.h then it can be ignored.

**Pull request merged**
