### PR TITLE
Prevent auto-commit during rebalance

### PR DESCRIPTION
**Pull request by mhowlett**
resolves the commit fail issue reported in #3306 by disallowing auto commits whilst a rebalance is in progress.
does not resolve the partition shuffling issue.

### CODE REVIEW

**Comment by mhowlett** [comment]
on second thoughts, manual committing will need consideration as well. WIP.

**Comment by mhowlett** [comment]
see #3226

**Comment by pratikthakkar24** [comment]
hey @mhowlett  do you mean, we should not manually commit messages while rebalance is in progress ? (I have registered a rebalance callback).

**Comment by pratikthakkar24** [comment]
> on second thoughts, manual committing will need consideration as well. WIP.

If we are using manual commit and in case of one of the three consumers shut down, how do we get to know in the other two consumers that a rebalance is in progress in the broker and we should stop manually committing our offsets of other partitions because there is a rebalance activity going on in the broker ?

**Pull request closed without merging**
