### PR TITLE
Allow key to be used in pointer and length style.

### PR DESCRIPTION
**Pull request by rthalley**
patch fixed

### CODE REVIEW

**Comment by edenhill** [comment]
That sounds like a good plan, and I think the naming is okay too.
Do you want to give it a go?

**Comment by rthalley** [comment]
> On Mar 19, 2015, at 13:35, Magnus Edenhill <notifications@github.com> wrote:
> 
> That sounds like a good plan, and I think the naming is okay too.
> Do you want to give it a go?
> 
> 

Will do.  I'll incorporate all feedback too, and force push a single clean patch to my repo and resubmit the pull request.

**Comment by rthalley** [comment]
I have pushed a new clean patch that incorporates everything we discussed I think.

**Comment by edenhill** [comment]
Sorry for the delay, @rthalley are you still happy with this? If so I'll merge it.

**Comment by rthalley** [comment]
I am happy with it, and it's working too :)  Merge away!

**Pull request merged**
