### PR TITLE
CMake: Add check for GNU thread name setting support.

### PR DESCRIPTION
**Pull request by billygout**
Tested by building with cmake with and without successful compile of [by introducing a typo into]  `packaging/cmake/try_compile/pthread_setname_gnu_test.c`, and checking by running `gdb` on one of the `examples/` apps and checking the difference in the output of `disassemble thrd_setname`.

### CODE REVIEW

**Comment by edenhill** [comment]
Think you forgot the compile test file itself:
```
CMake Error at CMakeLists.txt:15 (add_executable):
  Cannot find source file:

    /project/repo/checkout/packaging/cmake/try_compile/pthread_setname_gnu_test.c
```

**Comment by billygout** [comment]
Doh! Thanks

**Comment by billygout** [comment]
fixed,rebased,force-pushed

**Comment by edenhill** [comment]
Thank you!

**Pull request merged**
