### PR TITLE
* include wincrypt.h

### PR DESCRIPTION
**Pull request by pavel-pimenov**
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0020	identifier "CERT_STORE_OPEN_EXISTING_FLAG" is undefined
Error (active)	E0020	identifier "CERT_STORE_PROV_SYSTEM" is undefined
Error (active)	E0020	identifier "CERT_STORE_READONLY_FLAG" is undefined
Error (active)	E0020	identifier "CERT_SYSTEM_STORE_CURRENT_USER"
Error (active)	E0020	identifier "HCERTSTORE" is undefined
Error (active)	E0020	identifier "PCCERT_CONTEXT" is undefined

### CODE REVIEW

**Comment by edenhill** [comment]
What is reporting these errors?

**Comment by pavel-pimenov** [comment]
изображение

**Comment by edenhill** [comment]
Interesting, what VS version?

**Comment by pavel-pimenov** [comment]
image

**Comment by edenhill** [comment]
Okay, good to know. Thanks :+1:

**Pull request merged**
