### PR TITLE
Cpp metadata

### PR DESCRIPTION
**Pull request by incessantier**
Merged @eugpermar 's work for issue #221 with latest master in response to #433.

### CODE REVIEW

**Comment by edenhill** [comment]
Thanks @eugpermar and @incessantier

**Comment by incessantier** [comment]
Sweet!  Thanks @edenhill...you're a rock star.

**Comment by edenhill** [comment]
:metal:

**Comment by incessantier** [comment]
Should it cross your mind, can you let me know the next time you merge master up into oct15?

**Comment by eugpermar** [comment]
glad to help! Thanks both!

**Comment by edenhill** [comment]
@incessantier merged

**Pull request merged**
