### PR TITLE
Update interface compile definitions for Windows using CMake

### LINKED ISSUE #1777: Question : Link error LNK2019 in C++ with Visual Studio 2015
Description
===========
Hello all,

I hava an issue to link my code .... Build is OK, but not link .... 

I tried to use Nuget package, but it's the same .... 

I added rdkafkacpp.h and rdkafka.h in my PublicInterface folder 

I have this error :

NGEventCb.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function "public: static unsigned char __cdecl NGEventCb::event_cb(class RdKafka::Event &)" (?event_cb@NGEventCb@@SAEAEAVEvent@RdKafka@@@Z)

How to reproduce
================
My .h
#ifndef NGEventCb_H
#define NGEventCb_H

#include "NGKafka.h"

#include "NGKafkaServices.h"

// System
#include "CATUnicodeString.h"
#include "CATBoolean.h"

#include "rdkafkacpp.h"

using namespace RdKafka;

//-----------------------------------------------------------------------

class ExportedByNGKafkaServices NGEventCb
{

public:
	static CATBoolean event_cb(Event &event);

	//-----------------------------------------------------------------------
};
#endif

My .cpp

#include "NGEventCb.h"

// NGSystem
#include "NGTrace.h"

CATBoolean NGEventCb::event_cb(Event &event) 
{
	NGDefineFunctionTrace(NGEventCb, hr);

	print_time();

	CATBoolean Run;

	switch (event.type())
	{
	case Event::EVENT_ERROR:
		std::cerr << "ERROR (" << err2str(event.err()) << "): " <<
			event.str() << std::endl;
		if (event.err() == ERR__ALL_BROKERS_DOWN)
			Run = false;
		break;

	case Event::EVENT_STATS:
		std::cerr << "\"STATS\": " << event.str() << std::endl;
		break;

	case Event::EVENT_LOG:
		fprintf(stderr, "LOG-%i-%s: %s\n",
			event.severity(), event.fac().c_str(), event.str().c_str());
		break;

	case Event::EVENT_THROTTLE:
		std::cerr << "THROTTLED: " << event.throttle_time() << "ms by " <<
			event.broker_name() << " id " << (int)event.broker_id() << std::endl;
		break;

	default:
		std::cerr << "EVENT " << event.type() <<
			" (" << err2str(event.err()) << "): " <<
			event.str() << std::endl;
		break;
	}

	return Run;
}

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.4
 - [x] Apache Kafka version: `1.1.0
 - [x] librdkafka client configuration: `N/A
 - [x] Operating system: `Windows 7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by raulbocanegra**
This fixes #1777

### CODE REVIEW

**Comment by raulbocanegra** [comment]
Hi @edenhill I am not sure why is failing on Travis. It seems to compile and past the tests.

**Comment by edenhill** [comment]
Can you please rebase this branch on master, it has conflicts. Thanks

**Comment by raulbocanegra** [comment]
Still the same Error on Travis:

`ERROR: [Errno 2] No such file or directory: '/var/lib/mock/el7-x86_64/root/etc/mtab'`

**Comment by edenhill** [comment]
The travis failure is unrelated (rpm mock is acting up for some reason), you can ignore it.

This branch still seems to have conflicts

**Comment by edenhill** [comment]
I think you want to do this:
```
$ git fetch  origin  # or the remote that is edenhill/librdkafka.git
$ git rebase origin/master   # or the remote that is edenhill..
```

**Comment by raulbocanegra** [comment]
I did the following:

```
$ git fetch  upstream # upstream = https://github.com/edenhill/librdkafka.git
$ git rebase upstream/master
```
Then resolved all the conflicts. After that, my branch origin/master and the current diverged so I did a git merge with origin (git@github.com:raulbocanegra/librdkafka.git) that showed conflicts which I resolved again and pushed. Hope this works. 
Sorry for all the ping pong but I didn't notice the conflict until the rebase, GitHub says there is no conflicts.

**Comment by edenhill** [comment]
Sorry, but github still reports conflicts.
It might be easier to checkout a new branch based on updated origin/master and then cherrypick your changes from your existing branch, then force-pushing the new branch to your PR branch, or opening a new PR.

**Comment by rbocanegra** [comment]
I'll try that

**Comment by edenhill** [comment]
Thank you for this!

**Pull request merged**
