### PR TITLE
Prevent int overflow while computing abs_timeout for producer request…

### PR DESCRIPTION
**Pull request by KseniyaYakil**
tried to prevent int overflow and avoid incorrect message timeout (#2015)

### CODE REVIEW

**Comment by edenhill** [comment]
Looks good!
This will be released in v1.0.0 (november)

**Comment by KseniyaYakil** [comment]
Could you tell me what the release flow is? I've expected you will merge this change to master so we could use master branch in production)) Or do you merge just before release?

**Comment by edenhill** [comment]
We typically create new releases from master, and when getting closer to release date we will tag release candidates (RC) and only merge Pull requests that are critical to the release.
As soon as the final release is out we'll merge any PRs that have been approved but were not critical for the release.
v0.11.6 will be released this week, after that we'll merge this PR.

**Comment by KseniyaYakil** [comment]
Thanks a lot))

**Pull request merged**
