### PR TITLE
Fix timestamp extraction for compressed messages

### PR DESCRIPTION
**Pull request by yunjing**
Currently timestamp extraction fails for compressed messages. It would report `-1` instead of the actual timestamp because the timestamps for compressed messages are stored at the block level. This PR passes down the header for the block to each of the uncompressed messages.

### CODE REVIEW

**Comment by yunjing** [comment]
@edenhill any suggestion on this? We are trying to open source a project in a week, but this bug is blocking us.

**Comment by edenhill** [comment]
Hey, I'll look at this during the weekend and get back to you.

**Comment by yunjing** [comment]
Thanks @edenhill. Really appreciated!

**Comment by qix** [comment]
Hi, we've just pushed an open source project for which we require these changes in order to run in production: https://github.com/smyte/kafka_store

For now we're recommending that users install our fork, which we'll revert as soon as this makes it into a release.

**Comment by edenhill** [comment]
Thanks!

**Comment by edenhill** [comment]
Can you verify the fix on your end, thanks?

**Comment by yunjing** [comment]
Verified that it worked by compiling kafkacat with librdkafka master and consuming from several topics in production.

We have not yet incorporated the latest librdkafka in our production services.

**Pull request closed without merging**
