### PR TITLE
Upgrade pacman before the full msys2 upgrade

### PR DESCRIPTION
**Pull request by neptoess**
This should fix the MinGW travis errors, e.g. https://travis-ci.org/github/edenhill/librdkafka/jobs/688737080

### CODE REVIEW

**Comment by neptoess** [comment]
@edenhill ,
Integration tests are taking a while, but the MinGW build is all green. Does this PR need anything else?

**Comment by neptoess** [comment]
Merge away

**Comment by ed-alertedh** [comment]
TL;DR: LGTM, also happy to merge this :)

**Comment by edenhill** [comment]
Thank you!

**Pull request merged**
